server:
  port: 8094
  servlet:    context-path: /
spring:  datasource:
    #引入druid数据源
    type: com.alibaba.druid.pool.DruidDataSource    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/jtdb?serverTimezone=GMT%2B8&useUnicode=true&characterEncoding=utf8&autoReconnect=true&allowMultiQueries=true
    username: root
    password: root
    
      
#mybatis-plush配置
mybatis-plus:
    #别名包  简化类型转化的写法
  type-aliases-package: com.jt.pojo
    #加载mybatis的映射文件
  mapper-locations: classpath:/mybatis/mappers/*.xml
    #开启驼峰映射
  configuration:
    map-underscore-to-camel-case: true
 
#dubbo配置项   
dubbo:
  scan:
    basePackages: com.jt  #配置包扫描
  application:            #服务名称必须定义
    name: provider-cart
  registry:               #注册中心
     address: zookeeper://192.168.192.132:2181?backup=192.168.192.133:2181,192.168.192.134:2181   #?backup=192.168.126.176:2182,192.168.126.176:2183
  protocol:
    name: dubbo           #zookeeper节点名称
    port: 20881           #RPC通信 dubbo内部通信端口 
 
 
#引入日志logging:  level:    com.jt.mapper: debug
      
  